FROM nginx:stable

RUN apt-get update \
    && apt-get install -y gnupg curl \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs npm libpng-dev nasm \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR /app

RUN rm /etc/nginx/conf.d/default.conf

COPY . /app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]